# This is a config for E2B sandbox template.
# You can use template ID (1e5fug7fnfpwm2dr32b3) or template name (co-dev-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("co-dev-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("co-dev-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('co-dev-test2')

team_id = "b5ba56c2-c02a-4dee-bc3e-9da37c5425c5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "co-dev-test2"
template_id = "1e5fug7fnfpwm2dr32b3"
